/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t gui_shbin[];
extern const uint8_t gui_shbin_end[];
#if __cplusplus >= 201103L
static constexpr size_t gui_shbin_size=372;
#else
static const size_t gui_shbin_size=372;
#endif
